version: '3'
services: 
  client:
    image: spotifyreact.azurecr.io/spotifyreactclient:v1
    ports:
      - '80:80'
    depends_on: 
      - api
  api:
    image: spotifyreact.azurecr.io/spotifyreactapi:v1
    ports:
      - '5000:5000'